services:
  - type: web
    name: ubuntutrade
    runtime: node
    buildCommand: apt-get update -qq && apt-get install -y php-cli && npm install
    startCommand: npm start
    envVars:
      - key: DB_SSL
        value: "true"
      - key: NODE_ENV
        value: production
